//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 07:06:09 PM IST 
//


package com.codecoop.interact.core.dto.sbar;



public class SectionDto {

  
    protected String name;
    protected SymptomsDto symptoms;
    protected Integer order;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public SymptomsDto getSymptoms() {
		return symptoms;
	}
	public void setSymptoms(SymptomsDto symptoms) {
		this.symptoms = symptoms;
	}
	public Integer getOrder() {
		return order;
	}
	public void setOrder(Integer order) {
		this.order = order;
	}

}
