//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 07:06:09 PM IST 
//


package com.codecoop.interact.core.dto.sbar;

public class SymptomDto {

   
    protected String name;
    protected String datatype;
    protected String sbarAttrCode;
    protected String carePathAttrCode;
    protected String value;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDatatype() {
		return datatype;
	}
	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}
	public String getSbarAttrCode() {
		return sbarAttrCode;
	}
	public void setSbarAttrCode(String sbarAttrCode) {
		this.sbarAttrCode = sbarAttrCode;
	}
	public String getCarePathAttrCode() {
		return carePathAttrCode;
	}
	public void setCarePathAttrCode(String carePathAttrCode) {
		this.carePathAttrCode = carePathAttrCode;
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
   
}
