//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 07:06:09 PM IST 
//


package com.codecoop.interact.core.dto.sbar;

import java.util.ArrayList;
import java.util.List;

public class SymptomsDto {

    protected List<SymptomDto> symptom;

   
    public void setSymptom(List<SymptomDto> symptom) {
		this.symptom = symptom;
	}


	public List<SymptomDto> getSymptom() {
        if (symptom == null) {
            symptom = new ArrayList<SymptomDto>();
        }
        return this.symptom;
    }

}
