package com.codecoop.interact.core.domain;

// Generated Jul 26, 2014 9:46:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AdmissionAttributes generated by hbm2java
 */
@Entity
@Table(name = "ADMISSION_ATTRIBUTES", catalog = "INTERACT", uniqueConstraints = @UniqueConstraint(columnNames = "ATTRIBUTE_CODE"))
public class AdmissionAttributes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7746856095984249824L;
	private Long id;
	private String attributeName;
	private String attributeCode;
	private String valueType;
	private String codeExplained;
	private String formAttribute;

	public AdmissionAttributes() {
	}

	public AdmissionAttributes(String attributeName, String attributeCode,
			String valueType, String codeExplained,String formAttribute) {
		this.attributeName = attributeName;
		this.attributeCode = attributeCode;
		this.valueType = valueType;
		this.codeExplained = codeExplained;
		this.formAttribute = formAttribute;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ATTRIBUTE_NAME", length = 100)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "ATTRIBUTE_CODE", unique = true, length = 100)
	public String getAttributeCode() {
		return this.attributeCode;
	}

	public void setAttributeCode(String attributeCode) {
		this.attributeCode = attributeCode;
	}

	@Column(name = "VALUE_TYPE", length = 100)
	public String getValueType() {
		return this.valueType;
	}

	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	@Column(name = "CODE_EXPLAINED", length = 300)
	public String getCodeExplained() {
		return this.codeExplained;
	}

	public void setCodeExplained(String codeExplained) {
		this.codeExplained = codeExplained;
	}
	
	@Column(name = "FORM_ATTRIB", length = 100)
	public String getFormAttribute() {
		return formAttribute;
	}

	public void setFormAttribute(String formAttribute) {
		this.formAttribute = formAttribute;
	}
	
	

}
