package com.codecoop.interact.core.domain;

// Generated Jul 26, 2014 9:46:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hospital generated by hbm2java
 */
@Entity
@Table(name = "HOSPITAL", catalog = "INTERACT")
public class Hospital implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2689217533993064243L;
	private Long id;
	private String hospitalName;
	private Date dateCreated;
	private String userCreated;
	private Date dateModified;
	private String userModified;
	
	private Set<HospitalAddress> hospitalAddresses = new HashSet<HospitalAddress>();
	
	private Set<HospitalContact> hospitalContacts = new HashSet<HospitalContact>();

	public Hospital() {
	}

	public Hospital(String hospitalName, Date dateCreated, String userCreated,
			Date dateModified, String userModified) {
		this.hospitalName = hospitalName;
		this.dateCreated = dateCreated;
		this.userCreated = userCreated;
		this.dateModified = dateModified;
		this.userModified = userModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "HOSPITAL_NAME", length = 150)
	public String getHospitalName() {
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CREATED", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "USER_CREATED", length = 50)
	public String getUserCreated() {
		return this.userCreated;
	}

	public void setUserCreated(String userCreated) {
		this.userCreated = userCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_MODIFIED", length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "USER_MODIFIED", length = 50)
	public String getUserModified() {
		return this.userModified;
	}

	public void setUserModified(String userModified) {
		this.userModified = userModified;
	}

	public void setHospitalAddresses(Set<HospitalAddress> hospitalAddresses) {
		this.hospitalAddresses = hospitalAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	//@JoinColumn(name="HOSPITAL_ID")
	public Set<HospitalAddress> getHospitalAddresses() {
		return hospitalAddresses;
	}

	public void setHospitalContacts(Set<HospitalContact> hospitalContacts) {
		this.hospitalContacts = hospitalContacts;
	}
	
	@OneToMany(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	//@JoinColumn(name="HOSPITAL_ID")
	public Set<HospitalContact> getHospitalContacts() {
		return hospitalContacts;
	}

}
