package com.codecoop.interact.core.domain;

// Generated Jul 26, 2014 9:46:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HospitalCareTeam generated by hbm2java
 */
@Entity
@Table(name = "HOSPITAL_CARE_TEAM", catalog = "INTERACT")
public class HospitalCareTeam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2657580110671819265L;
	private Long id;
	private Long hospitalStaffId;
	private Long patientEpisodeId;
	private Long hsptlStaffSpecialityId;
	private Date dateCreated;
	private String userCreated;
	private Date dateModified;
	private String userModified;

	public HospitalCareTeam() {
	}

	public HospitalCareTeam(Long hospitalStaffId, Long patientEpisodeId,
			Long hsptlStaffSpecialityId,
			Date dateCreated, String userCreated, Date dateModified,
			String userModified) {
		this.hospitalStaffId = hospitalStaffId;
		this.patientEpisodeId = patientEpisodeId;
		this.hsptlStaffSpecialityId = hsptlStaffSpecialityId;
		this.dateCreated = dateCreated;
		this.userCreated = userCreated;
		this.dateModified = dateModified;
		this.userModified = userModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "HOSPITAL_STAFF_ID")
	public Long getHospitalStaffId() {
		return this.hospitalStaffId;
	}

	public void setHospitalStaffId(Long hospitalStaffId) {
		this.hospitalStaffId = hospitalStaffId;
	}

	@Column(name = "PATIENT_EPISODE_ID")
	public Long getPatientEpisodeId() {
		return this.patientEpisodeId;
	}

	public void setPatientEpisodeId(Long patientEpisodeId) {
		this.patientEpisodeId = patientEpisodeId;
	}

	@Column(name = "HSPTL_STAFF_SPECIALITY_ID")
	public Long getHsptlStaffSpecialityId() {
		return this.hsptlStaffSpecialityId;
	}

	public void setHsptlStaffSpecialityId(Long hsptlStaffSpecialityId) {
		this.hsptlStaffSpecialityId = hsptlStaffSpecialityId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CREATED", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "USER_CREATED", length = 50)
	public String getUserCreated() {
		return this.userCreated;
	}

	public void setUserCreated(String userCreated) {
		this.userCreated = userCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_MODIFIED", length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "USER_MODIFIED", length = 50)
	public String getUserModified() {
		return this.userModified;
	}

	public void setUserModified(String userModified) {
		this.userModified = userModified;
	}

}
