package com.codecoop.interact.core.domain;

// Generated Jul 26, 2014 9:46:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HospitalStaff generated by hbm2java
 */
@Entity
@Table(name = "HOSPITAL_STAFF", catalog = "INTERACT"/*, uniqueConstraints = @UniqueConstraint(columnNames = "CONTACTNO")*/)
public class HospitalStaff implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1917762735591279533L;
	private Long id;
	private Long hsptlStaffTypeId;
	private Long specialityId;
	private Long patientEncounterId;
//	private PatientEpisode patientEpisode;
	private String staffName;
	private String contactno;
	private String emailid;
	private Date dateCreated;
	private String userCreated;
	private Date dateModified;
	private String userModified;

	public HospitalStaff() {
	}

	public HospitalStaff(String staffName,Long hsptlStaffTypeId,Long specialityId,Long patientEncounterId,String contactno, String emailid,
			Date dateCreated, String userCreated, Date dateModified,
			String userModified) {
		this.staffName = staffName;
		this.hsptlStaffTypeId = hsptlStaffTypeId;
		this.specialityId = specialityId;
		this.patientEncounterId =patientEncounterId;
		this.contactno = contactno;
		this.emailid = emailid;
		this.dateCreated = dateCreated;
		this.userCreated = userCreated;
		this.dateModified = dateModified;
		this.userModified = userModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "HSPTL_STAFF_TYPE_ID")
	public Long getHsptlStaffTypeId() {
		return hsptlStaffTypeId;
	}

	public void setHsptlStaffTypeId(Long hsptlStaffTypeId) {
		this.hsptlStaffTypeId = hsptlStaffTypeId;
	}

	@Column(name ="SPECIALITY_ID")
	public Long getSpecialityId() {
		return specialityId;
	}

	public void setSpecialityId(Long specialityId) {
		this.specialityId = specialityId;
	}
////	@ManyToOne(fetch=FetchType.LAZY)
//	@JoinColumn(name ="PATIENT_EPISODE_ID")
//	public Long getPatientEpisodeId() {
//		return patientEpisodeId;
//	}
//
//	public void setPatientEpisodeId(Long patientEpisodeId) {
//		this.patientEpisodeId = patientEpisodeId;
//	}
	@Column(name = "PATIENT_ENCOUNTER_ID")
	public Long getPatientEncounterId() {
		return patientEncounterId;
	}

	public void setPatientEncounterId(Long patientEncounterId) {
		this.patientEncounterId = patientEncounterId;
	}
	
	@Column(name = "STAFF_NAME", length = 150)
	public String getStaffName() {
		return this.staffName;
	}
	
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Column(name = "CONTACTNO")
	public String getContactno() {
		return this.contactno;
	}

	public void setContactno(String contactno) {
		this.contactno = contactno;
	}

	@Column(name = "EMAILID", length = 30)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CREATED", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "USER_CREATED", length = 50)
	public String getUserCreated() {
		return this.userCreated;
	}

	public void setUserCreated(String userCreated) {
		this.userCreated = userCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_MODIFIED", length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "USER_MODIFIED", length = 50)
	public String getUserModified() {
		return this.userModified;
	}

	public void setUserModified(String userModified) {
		this.userModified = userModified;
	}

}
