package com.codecoop.interact.core.domain;

// Generated Aug 30, 2014 3:46:09 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MedicalReconciliation generated by hbm2java
 */
@Entity
@Table(name = "MEDICAL_RECONCILIATION", catalog = "INTERACT")
public class MedicalReconciliation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2763878407447632206L;
	private Long id;
	private Long patientEncounterId;
	private String medicineDetail;
	private String medicineRecommendation;
	private String clarificationNeeded;
	private Long medicineResolutionId;
	private String comments;
	private Date dateCreated;
	private String userCreated;
	private Date dateModified;
	private String userModified;

	public MedicalReconciliation() {
	}

	public MedicalReconciliation(Long patientEncounterId, String medicineDetail,
			String medicineRecommendation, String clarificationNeeded,
			Long medicineResolutionId, String comments, Date dateCreated,
			String userCreated, Date dateModified, String userModified) {
		this.patientEncounterId = patientEncounterId;
		this.medicineDetail = medicineDetail;
		this.medicineRecommendation = medicineRecommendation;
		this.clarificationNeeded = clarificationNeeded;
		this.medicineResolutionId = medicineResolutionId;
		this.comments = comments;
		this.dateCreated = dateCreated;
		this.userCreated = userCreated;
		this.dateModified = dateModified;
		this.userModified = userModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "PATIENT_ENCOUNTER_ID")
	public Long getPatientEncounterId() {
		return patientEncounterId;
	}

	public void setPatientEncounterId(Long patientEncounterId) {
		this.patientEncounterId = patientEncounterId;
	}

	@Column(name = "MEDICINE_DETAIL", length = 25)
	public String getMedicineDetail() {
		return this.medicineDetail;
	}

	public void setMedicineDetail(String medicineDetail) {
		this.medicineDetail = medicineDetail;
	}

	@Column(name = "MEDICINE_RECOMMENDATION")
	public String getMedicineRecommendation() {
		return this.medicineRecommendation;
	}

	public void setMedicineRecommendation(String medicineRecommendation) {
		this.medicineRecommendation = medicineRecommendation;
	}

	@Column(name = "CLARIFICATION_NEEDED", length = 250)
	public String getClarificationNeeded() {
		return this.clarificationNeeded;
	}

	public void setClarificationNeeded(String clarificationNeeded) {
		this.clarificationNeeded = clarificationNeeded;
	}

	@Column(name = "MEDICINE_RESOLUTION_ID")
	public Long getMedicineResolutionId() {
		return this.medicineResolutionId;
	}

	public void setMedicineResolutionId(Long medicineResolutionId) {
		this.medicineResolutionId = medicineResolutionId;
	}

	@Column(name = "COMMENTS", length = 250)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CREATED", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "USER_CREATED", length = 50)
	public String getUserCreated() {
		return this.userCreated;
	}

	public void setUserCreated(String userCreated) {
		this.userCreated = userCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_MODIFIED", length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "USER_MODIFIED", length = 50)
	public String getUserModified() {
		return this.userModified;
	}

	public void setUserModified(String userModified) {
		this.userModified = userModified;
	}

}
