package com.codecoop.interact.core.domain;


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
// * PatientEpisode generated by hbm2java
 */
@Entity
@Table(name = "PATIENT_EPISODE", catalog = "INTERACT")
public class PatientEpisode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1071557677240477124L;
	private Long id;
	private Patient patient;
	private Long guardianId;
	private Long facilityId;
/*	private Long fromHospitalId;
	private Date fromHsptalAdmissionDate;
	private Date fromHsptalDischargeDate;
	private String formHospitalUnit;*/
	//	private Long hsptalDischargeNurseId;
	//	private Long hsptalDischargeDoctorId;
	private Date facilityAdmissionDate;
	private Date facilityDischargeDate;
	private Long facilityDischargeRnId;
	private Long facilityDischargeMdId;
	private Long toHospitalId;
	private String bedNo;
	private String roomNumber;
	private String listProcedures;
	private String keyFindings;
	private String hsptalPriorityCareNeeds;
	private String pendingLabResult;
	private String followUpTests;
	private String fullCode;
	private Boolean dnr;
	private Boolean dni;
	private Boolean dnh;
	private Boolean noArtificialFeeding;
	private Boolean comfortCare;
	private Boolean hospiceCare;
	private String otherCare;
	private String goalsCareDiscussionText;
	private String canTakeDecision;
	private String goalsOfCareDiscussed;
	private String reqProxy;
	private String nurseToNurseVerbalReport;
	private String hospitalNurseVerbalReport;
	private Long admittedByStaffId;
	private Date dateCreated;
	private String userCreated;
	private Date dateModified;
	private String userModified;
	private String toHsptalUnit;
	private String facilityStayType;
	private Boolean stopAndWatchEligible;
	private Boolean sbarRised;
	private Long pcpId;
//	private List<HospitalStaff> careTeam;
	private String msgScenarioCode;
	private String patientCareTypes;
	private String patientInsurencePlan;
	//	private Set<HospitalCareTeam> hospitalCareTeam;
	private List<AdmissionAttributesValues> admissionAttributesValuesList;
	public PatientEpisode() {
	}
	public PatientEpisode(Patient patient, Long guardianId, Long facilityId,
			Date facilityAdmissionDate, Date facilityDischargeDate,
			Long facilityDischargeRnId, Long facilityDischargeMdId,
			Long toHospitalId, String bedNo, String listProcedures,
			String keyFindings, String hsptalPriorityCareNeeds,
			String pendingLabResult, String followUpTests, String fullCode,
			Boolean dnr, Boolean dni, Boolean dnh, Boolean noArtificialFeeding,Boolean hospiceCare,
			Boolean comfortCare, String otherCare,
			String goalsCareDiscussionText, String canTakeDecision,String goalsOfCareDiscussed,String reqProxy,String nurseToNurseVerbalReport,
			String hospitalNurseVerbalReport, Long admittedByStaffId,
			Date dateCreated, String userCreated, Date dateModified,
			String userModified, String toHsptalUnit, String facilityStayType,Boolean stopAndWatchEligible,Long pcpId,String patientCareTypes,String patientInsurencePlan  		
			) {
		super();
		this.patient = patient;
		this.guardianId = guardianId;
		this.facilityId = facilityId;
		this.facilityAdmissionDate = facilityAdmissionDate;
		this.facilityDischargeDate = facilityDischargeDate;
		this.facilityDischargeRnId = facilityDischargeRnId;
		this.facilityDischargeMdId = facilityDischargeMdId;
		this.toHospitalId = toHospitalId;
		this.bedNo = bedNo;
		this.listProcedures = listProcedures;
		this.keyFindings = keyFindings;
		this.hsptalPriorityCareNeeds = hsptalPriorityCareNeeds;
		this.pendingLabResult = pendingLabResult;
		this.followUpTests = followUpTests;
		this.fullCode = fullCode;
		this.dnr = dnr;
		this.dni = dni;
		this.dnh = dnh;
		this.noArtificialFeeding = noArtificialFeeding;
		this.comfortCare = comfortCare;
		this.hospiceCare = hospiceCare;
		this.otherCare = otherCare;
		this.goalsCareDiscussionText = goalsCareDiscussionText;
		this.canTakeDecision = canTakeDecision;
		this.hospitalNurseVerbalReport = hospitalNurseVerbalReport;
		this.admittedByStaffId = admittedByStaffId;
		this.dateCreated = dateCreated;
		this.userCreated = userCreated;
		this.dateModified = dateModified;
		this.userModified = userModified;
		this.toHsptalUnit = toHsptalUnit;
		this.facilityStayType = facilityStayType;
		this.stopAndWatchEligible = stopAndWatchEligible;
		this.pcpId= pcpId;
		this.goalsOfCareDiscussed = goalsOfCareDiscussed;
		this.reqProxy = reqProxy;
		this.nurseToNurseVerbalReport = nurseToNurseVerbalReport;
		this.patientCareTypes = patientCareTypes;
		this.patientInsurencePlan=patientInsurencePlan;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PATIENT_ID")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "GUARDIAN_ID")
	public Long getGuardianId() {
		return this.guardianId;
	}

	public void setGuardianId(Long guardianId) {
		this.guardianId = guardianId;
	}

	@Column(name = "FACILITY_ID")
	public Long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(Long facilityId) {
		this.facilityId = facilityId;
	}



	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FACILITY_DISCHARGE_DATE", length = 19)
	public Date getFacilityDischargeDate() {
		return this.facilityDischargeDate;
	}

	public void setFacilityDischargeDate(Date facilityDischargeDate) {
		this.facilityDischargeDate = facilityDischargeDate;
	}

	@Column(name = "FACILITY_DISCHARGE_RN_ID")
	public Long getFacilityDischargeRnId() {
		return this.facilityDischargeRnId;
	}

	public void setFacilityDischargeRnId(Long facilityDischargeRnId) {
		this.facilityDischargeRnId = facilityDischargeRnId;
	}

	@Column(name = "FACILITY_DISCHARGE_MD_ID")
	public Long getFacilityDischargeMdId() {
		return this.facilityDischargeMdId;
	}

	public void setFacilityDischargeMdId(Long facilityDischargeMdId) {
		this.facilityDischargeMdId = facilityDischargeMdId;
	}

	@Column(name = "TO_HOSPITAL_ID")
	public Long getToHospitalId() {
		return this.toHospitalId;
	}

	public void setToHospitalId(Long toHospitalId) {
		this.toHospitalId = toHospitalId;
	}

	@Column(name = "BED_NO", length = 60)
	public String getBedNo() {
		return this.bedNo;
	}

	public void setBedNo(String bedNo) {
		this.bedNo = bedNo;
	}
	@Column(name = "ROOM_NUMBER", length = 30)
	public String getRoomNumber() {
		return roomNumber;
	}
	public void setRoomNumber(String roomNumber) {
		this.roomNumber = roomNumber;
	}
	@Column(name = "LIST_PROCEDURES", length = 200)
	public String getListProcedures() {
		return this.listProcedures;
	}

	public void setListProcedures(String listProcedures) {
		this.listProcedures = listProcedures;
	}

	@Column(name = "KEY_FINDINGS", length = 100)
	public String getKeyFindings() {
		return this.keyFindings;
	}

	public void setKeyFindings(String keyFindings) {
		this.keyFindings = keyFindings;
	}




	@Column(name = "PENDING_LAB_RESULT", length = 150)
	public String getPendingLabResult() {
		return this.pendingLabResult;
	}

	public void setPendingLabResult(String pendingLabResult) {
		this.pendingLabResult = pendingLabResult;
	}

	@Column(name = "FOLLOW_UP_TESTS", length = 150)
	public String getFollowUpTests() {
		return this.followUpTests;
	}

	public void setFollowUpTests(String followUpTests) {
		this.followUpTests = followUpTests;
	}

	@Column(name = "FULL_CODE", length = 150)
	public String getFullCode() {
		return this.fullCode;
	}

	public void setFullCode(String fullCode) {
		this.fullCode = fullCode;
	}

	@Column(name = "DNR")
	public Boolean getDnr() {
		return this.dnr;
	}

	public void setDnr(Boolean dnr) {
		this.dnr = dnr;
	}

	@Column(name = "DNI")
	public Boolean getDni() {
		return this.dni;
	}

	public void setDni(Boolean dni) {
		this.dni = dni;
	}

	@Column(name = "DNH")
	public Boolean getDnh() {
		return this.dnh;
	}
	public void setDnh(Boolean dnh) {
		this.dnh = dnh;
	}
	
	@Column(name = "SBAR_RISED")
	public Boolean getSbarRised() {
		return sbarRised;
	}
	public void setSbarRised(Boolean sbarRised) {
		this.sbarRised = sbarRised;
	}
	
	@Column(name = "PCP_ID")
	public Long getPcpId() {
		return pcpId;
	}
	public void setPcpId(Long pcpId) {
		this.pcpId = pcpId;
	}
	
	@Column(name = "NO_ARTIFICIAL_FEEDING")
	public Boolean getNoArtificialFeeding() {
		return this.noArtificialFeeding;
	}

	public void setNoArtificialFeeding(Boolean noArtificialFeeding) {
		this.noArtificialFeeding = noArtificialFeeding;
	}

	@Column(name = "COMFORT_CARE")
	public Boolean getComfortCare() {
		return this.comfortCare;
	}

	public void setComfortCare(Boolean comfortCare) {
		this.comfortCare = comfortCare;
	}
	@Column(name = "HOSPICE_CARE")
	public Boolean getHospiceCare() {
		return hospiceCare;
	}
	public void setHospiceCare(Boolean hospiceCare) {
		this.hospiceCare = hospiceCare;
	}

	@Column(name = "OTHER_CARE", length = 200)
	public String getOtherCare() {
		return this.otherCare;
	}

	public void setOtherCare(String otherCare) {
		this.otherCare = otherCare;
	}

	@Column(name = "GOALS_CARE_DISCUSSION_TEXT", length = 200)
	public String getGoalsCareDiscussionText() {
		return this.goalsCareDiscussionText;
	}

	public void setGoalsCareDiscussionText(String goalsCareDiscussionText) {
		this.goalsCareDiscussionText = goalsCareDiscussionText;
	}

	@Column(name = "CAN_TAKE_DECISION")
	public String getCanTakeDecision() {
		return canTakeDecision;
	}

	public void setCanTakeDecision(String canTakeDecision) {
		this.canTakeDecision = canTakeDecision;
	}
	
	@Column(name = "GOALS_OF_CAREDISCUSSED")
	public String getGoalsOfCareDiscussed() {
		return goalsOfCareDiscussed;
	}
	public void setGoalsOfCareDiscussed(String goalsOfCareDiscussed) {
		this.goalsOfCareDiscussed = goalsOfCareDiscussed;
	}
	
	@Column(name = "REQ_PROXY")
	public String getReqProxy() {
		return reqProxy;
	}
	public void setReqProxy(String reqProxy) {
		this.reqProxy = reqProxy;
	}
	
	@Column(name = "NURSE_TO_NURSE_VERBAL_REPORT")
	public String getNurseToNurseVerbalReport() {
		return nurseToNurseVerbalReport;
	}
	public void setNurseToNurseVerbalReport(String nurseToNurseVerbalReport) {
		this.nurseToNurseVerbalReport = nurseToNurseVerbalReport;
	}
	
	@Column(name = "HOSPITAL_NURSE_VERBAL_REPORT", length = 200)
	public String getHospitalNurseVerbalReport() {
		return this.hospitalNurseVerbalReport;
	}

	public void setHospitalNurseVerbalReport(String hospitalNurseVerbalReport) {
		this.hospitalNurseVerbalReport = hospitalNurseVerbalReport;
	}

	@Column(name = "ADMITTED_BY_STAFF_ID")
	public Long getAdmittedByStaffId() {
		return this.admittedByStaffId;
	}

	public void setAdmittedByStaffId(Long admittedByStaffId) {
		this.admittedByStaffId = admittedByStaffId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CREATED", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "USER_CREATED", length = 50)
	public String getUserCreated() {
		return this.userCreated;
	}

	public void setUserCreated(String userCreated) {
		this.userCreated = userCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_MODIFIED", length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "USER_MODIFIED", length = 50)
	public String getUserModified() {
		return this.userModified;
	}

	public void setUserModified(String userModified) {
		this.userModified = userModified;
	}

	/*//  @ManyToOne(fetch=FetchType.EAGER )
	@Column(name = "FROM_HOSPITAL_ID")
	public Long getFromHospitalId() {
		return fromHospitalId;
	}

	public void setFromHospitalId(Long fromHospitalId) {
		this.fromHospitalId = fromHospitalId;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FROM_HSPTAL_ADMISSION_DATE", length = 19)
	public Date getFromHsptalAdmissionDate() {
		return fromHsptalAdmissionDate;
	}



	public void setFromHsptalAdmissionDate(Date fromHsptalAdmissionDate) {
		this.fromHsptalAdmissionDate = fromHsptalAdmissionDate;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FROM_HSPTAL_DISCHARGE_DATE", length = 19)
	public Date getFromHsptalDischargeDate() {
		return fromHsptalDischargeDate;
	}
	public void setFromHsptalDischargeDate(Date fromHsptalDischargeDate) {
		this.fromHsptalDischargeDate = fromHsptalDischargeDate;
	}


	//	@Column(name = "HSPTL_DISCHARGE_NURSE_ID")
	//	public Long getHsptalDischargeNurseId() {
	//		return hsptalDischargeNurseId;
	//	}
	//	public void setHsptalDischargeNurseId(Long hsptalDischargeNurseId) {
	//		this.hsptalDischargeNurseId = hsptalDischargeNurseId;
	//	}
	//
	//
	//	@Column(name = "HSPTL_DISCHARGE_DOCTOR_ID")
	//	public Long getHsptalDischargeDoctorId() {
	//		return hsptalDischargeDoctorId;
	//	}
	//
	//   public void setHsptalDischargeDoctorId(Long hsptalDischargeDoctorId) {
	//		this.hsptalDischargeDoctorId = hsptalDischargeDoctorId;
	//	}


	@Column(name = "FORM_HOSPITAL_UNIT", length = 25)
	public String getFormHospitalUnit() {
		return formHospitalUnit;
	}

	public void setFormHospitalUnit(String formHospitalUnit) {
		this.formHospitalUnit = formHospitalUnit;
	}*/


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FACILITY_ADMISSION_DATE", length = 19)
	public Date getFacilityAdmissionDate() {
		return facilityAdmissionDate;
	}

	public void setFacilityAdmissionDate(Date facilityAdmissionDate) {
		this.facilityAdmissionDate = facilityAdmissionDate;
	}


	@Column(name = "HSPTL_PRIORITY_CARE_NEEDS", length = 200)
	public String getHsptalPriorityCareNeeds() {
		return hsptalPriorityCareNeeds;
	}

	public void setHsptalPriorityCareNeeds(String hsptalPriorityCareNeeds) {
		this.hsptalPriorityCareNeeds = hsptalPriorityCareNeeds;
	}


	@Column(name = "TO_HOSPITAL_UNIT", length = 25)
	public String getToHsptalUnit() {
		return toHsptalUnit;
	}



	public void setToHsptalUnit(String toHsptalUnit) {
		this.toHsptalUnit = toHsptalUnit;
	}

	@Column(name = "FACILITY_STAY_TYPE", length = 25)
	public String getFacilityStayType() {
		return facilityStayType;
	}

	public void setFacilityStayType(String facilityStayType) {
		this.facilityStayType = facilityStayType;
	}
	
	@Column(name = "S_AND_W_ELIGIBLE")
	public Boolean getStopAndWatchEligible() {
		return stopAndWatchEligible;
	}
	public void setStopAndWatchEligible(Boolean stopAndWatchEligible) {
		this.stopAndWatchEligible = stopAndWatchEligible;
	}
	//	@OneToMany(cascade={CascadeType.ALL}, mappedBy="patientEpisode")
/*	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	@JoinColumn(name="PATIENT_EPISODE_ID")
	public List<HospitalStaff> getCareTeam() {
		return careTeam;
	}
	public void setCareTeam(List<HospitalStaff> careTeam) {
		this.careTeam = careTeam;
	}*/
	public void setAdmissionAttributesValuesList(
			List<AdmissionAttributesValues> admissionAttributesValuesList) {
		this.admissionAttributesValuesList = admissionAttributesValuesList;
	}

	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	@JoinColumn(name="P_EPISODE_ID")
	public List<AdmissionAttributesValues> getAdmissionAttributesValuesList() {
		return admissionAttributesValuesList;
	}
	@Column(name ="MSG_SCENARIO_CODE")
	public String getMsgScenarioCode() {
		return msgScenarioCode;
	}
	public void setMsgScenarioCode(String msgScenarioCode) {
		this.msgScenarioCode = msgScenarioCode;
	}
	@Column(name ="CARE_TYPES")
	public String getPatientCareTypes() {
		return patientCareTypes;
	}
	public void setPatientCareTypes(String patientCareTypes) {
		this.patientCareTypes = patientCareTypes;
	}
	@Column(name ="INSURENCE_PLAN")
	public String getPatientInsurencePlan() {
		return patientInsurencePlan;
	}
	public void setPatientInsurencePlan(String patientInsurencePlan) {
		this.patientInsurencePlan = patientInsurencePlan;
	}

}
